[package]
name = "wasi-sql-error"
version = "0.1.0"
edition = "2024"

[dependencies]
rusqlite = {version = "0.37.0", features = ["bundled", "wasm32-wasi-vfs"] }

[build-dependencies]
env = "1.0.1"
glob = "0.3.3"

